#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# only check formatting of modified or newly added files
CHANGED_FILES=$(git --no-pager diff --name-only --cached --diff-filter=AM --relative -- \
  '*.md' '*.html' '*.yml' '*.yaml' '*.json' '*.js' '*.jsx' '*.ts' '*.tsx' '*.css')

if [ -n "$CHANGED_FILES" ]; then
  pnpm dlx prettier --check $CHANGED_FILES
fi

pnpm lint
pnpm typecheck
pnpm run test:unit
